### ISSUE TITLE
Update README to include vimrc lines to use color scheme and airline theme

### ISSUE THREAD

**Issue by clbarnes** [danilo-augusto/vim-afterglow#5]
Love the color scheme, but I'm probably not the only person in the world new to vim configuration!

**Comment by danilo-augusto** [comment]
Hi! Thank you for the compliment. :) 
Well, I think this is not an issue in itself as much as a clarification, but I will try to help you the most (sorry for the big delay).

Most probably it suffices to add `colorscheme afterglow` (or simply `colo afterglow` to abbreviate)  to your $HOME/.vimrc after having imported the project, which can be done the old way (downloading the repo with a git clone inside the ~/.vim/autoload folder) or using a package manager, which I highly recommend (I personally use [vim-plug](https://github.com/junegunn/vim-plug)).
You can learn more about `colorscheme` by typing `:help colorscheme`.

Regarding your airline theme, you don't have to do anything. :)
When this colorscheme is set, it automatically sets the airline theme too (which you can override of course).
However, if you want to be explicit about it, you can perfectly write
```
let g:airline_theme='afterglow'
```

You are right, I could specify the line because it can be ambiguous to new people: "is it colorscheme airline?", "is it colorscheme vim-airline?" etc.
So thanks for the feedback, I will add this to the README.

**Comment by danilo-augusto** [comment]
Done in #7.

**Comment by clbarnes** [comment]
Thanks, that's what I was after! I didn't know whether it was `afterglow`, `Afterglow`, `vim-afterglow` etc.
